lime3ds-gui: Add Custom Layout interface to Enhancements tab
azahar-emu/azahar pull request #204
Opened 2024-05-22 04:59 UTC by rtiangha

This is another PR that was submitted for consideration (this time by [blakbin](https://github.com/blakbin/citra/commits/custom_layout/)) but never had a chance to make it into Canary or Nightly before the shutdown. The consensus seemed to be that it’d be merged in once the Configuration UI received a general overhaul, but that never had a chance to happen.

It gives an interface to the hidden Custom Layout functionality where you can explicitly specify the placement of the two screens. The functionality to do so was always there and could be specified via one of the text configuration files; this PR just gives the user a graphical way to do so.

As an example (see below), you could make one screen really big and the other really small, and even put one on top of the other and adjust the opacity of that second screen (unfortunately, customizable opacity is OpenGL only).

Some screenshots:

Configuration Interface
![configuration](https://github.com/Lime3DS/Lime3DS/assets/8913195/2a68c02d-25f7-4f7f-8100-ce94881dcd52)

Example: Picture-in-Picture placement with second screen at 75% opacity
![pip](https://github.com/Lime3DS/Lime3DS/assets/8913195/3d1530e1-a97e-4633-92b5-c0c2ee0f882c)

Position values are in pixels starting from (0,0) (i.e. the top left of the display), which are the units that the original text-based functionality uses. Opacity is in percent.

Original Description:

> This add Custom Layout selector in Both Menu and Enhancement Setting. This will allow to use or change Custom Layout mode or by using toggle no matter what config 'custom_layout\default' value true or false. Still No Overlay Editor, just manual edit box, and this Not saved or carried at per game settings.

[Original PR](https://web.archive.org/web/20240107122308/https://github.com/citra-emu/citra/pull/6532)

2024-05-23 16:40 UTC, Gamer64ytb commented
I think that we should add a layout editor before just a toggle as well, but I don't think it's a easy task so idk

2024-05-23 17:49 UTC, OpenSauce04 commented
> I think that we should add a layout editor before just a toggle as well

Not sure what you mean, this isn't just a toggle. The menu itself is the editor.

If you are referring to a graphical editor where you can drag the windows around and stuff, that would likely require a large amount of work, and isn't an immediate concern when compared to the immediate benefits this implementation gives in its current state.

2024-05-23 17:51 UTC, OpenSauce04 commented
Given that this new feature doesn't really qualify as an 'enhancement' and takes up quite a large space in the menu, I think it would be beneficial to move this to a new tab named "Layout". What are your thoughts on this?

2024-05-23 18:38 UTC, rtiangha commented
Good thing I can see the future, lol. I'll push things out once I've confirmed they compile on this end. Shouldn't be too long since I've already done the work.

2024-05-23 18:47 UTC, OpenSauce04 commented
I will hopefully get around to reviewing all of your PRs on Saturday and Sunday. Thank you for all of the contributions.

2024-05-23 19:10 UTC, rtiangha commented
And done. New screenshots:

Enhancements Tab
![enhancements](https://github.com/Lime3DS/Lime3DS/assets/8913195/f5642bbb-cb8f-4862-9902-7910c1ba0003)

Layout Tab
![newlayout](https://github.com/Lime3DS/Lime3DS/assets/8913195/a238692d-c236-4bc6-8835-05811a2e2ed2)

2024-05-25 20:21 UTC, OpenSauce04 requested changes

2024-05-25 20:21 UTC, OpenSauce04 commented on src/lime_qt/configuration/configure_enhancements.ui
> -           </item>
The 'Hybrid Screen' layout option is missing from the Layout configuration menu

2024-05-25 20:30 UTC, OpenSauce04 commented
The 'Hybrid Layout' view option appears to be missing from the Layout configuration tab 
![image](https://github.com/Lime3DS/Lime3DS/assets/48618519/8760710a-df05-4b1b-a248-46573d66e36f)
Selecting Hybrid Layout in the View menu causes Custom Layout to be selected in this menu, and selecting Custom Layout in the View menu causes no option to be selected in this menu:
![image](https://github.com/Lime3DS/Lime3DS/assets/48618519/bf8df19c-075a-4347-a6dd-57c1727737f0)

2024-05-26 04:44 UTC, rtiangha commented
OK, I think that should do it, but please verify. I also took the opportunity to reorder the View menu to match the Layout drop down order to make things more consistent and to satisfy my OCD.

2024-05-26 13:42 UTC, OpenSauce04 commented
This PR functions fine, however I would like to change how this functionality is implemented from a UX perspective.
While the currently implemented Top, Bottom, Left, Right setup works, it is not particularly intuitive. I would like to swap this out for a conventional X, Y, Width, Height setup, as this is much easier to understand and manipulate than setting absolute positions for each of the screen's edges.

2024-05-26 17:47 UTC, rtiangha commented
Have at 'er.

2024-05-26 18:49 UTC, OpenSauce04 commented
![image](https://github.com/Lime3DS/Lime3DS/assets/48618519/e8f12e4f-4aab-4a32-9bfa-3c2bd541b9b6)
What is this value supposed to do exactly? I can't seem to get any discernible effect out of changing it

2024-05-26 18:58 UTC, OpenSauce04 commented
Oh, it's a value exclusive to the Large Screen view option, and changes the size each screen takes up. This should be greyed out when other layouts are selected to avoid confusion. I will implement this change along with my previously mentioned amendments

2024-05-26 19:00 UTC, rtiangha commented
It was there before the patch. That said, I think for at least one of the layout modes (can't remember which one(s)), it affects how large the main screen is relative to the secondary screen. I think it's supposed to be a convenience thing and was the only way for the user to resize screens before this patch. Would have no effect on the Custom Layout profile since it uses different variables.

2024-05-26 19:23 UTC, OpenSauce04 commented
I appear to still be unable to push my changes to your fork
![image](https://github.com/Lime3DS/Lime3DS/assets/48618519/ca63be05-797b-42a7-a5cf-c1a6746ed9af)

2024-05-26 21:07 UTC, rtiangha commented
Try it now.

2024-05-26 21:08 UTC, OpenSauce04 commented
New UI layout:
![image](https://github.com/Lime3DS/Lime3DS/assets/48618519/05b062e6-4c82-4ee9-b23d-45a3e404c7cb)

2024-05-26 21:09 UTC, rtiangha commented
Yeah, that is better.

2024-05-26 21:09 UTC, OpenSauce04 commented
As I have made notable changes to this PR, I am going to request that you also review the changes to get a second pair of eyes on my changes
As you created the PR, you cannot make a formal review, so please just state your opinion as a commit

2024-05-26 21:09 UTC, OpenSauce04 approved these changes

2024-05-26 21:46 UTC, rtiangha commented
LGTM, although I am a bit curious about why the need to cast to (u32). The values are defined as u16 to begin with; isn't 32-bits for something that's probably max 4 digits long a bit overkill?

2024-05-26 22:06 UTC, OpenSauce04 commented
The cast is simply to stop the compiler from whingeing when adding the two numbers together.
This is what happens when the cast is not present:
```
/var/host/home/daniel/repos/Lime3DS/src/core/frontend/framebuffer_layout.cpp:382:80: error: narrowing conversion of '(((int)Settings::values.Settings::Values::custom_top_x.Settings::Setting<short unsigned int>::GetValue()) + ((int)Settings::values.Settings::Values::custom_top_width.Settings::Setting<short unsigned int>::GetValue()))' from 'int' to 'unsigned int' [-Werror=narrowing]
```
u32 was chosen instead of u16 to avoid a case where both a maximum size X/Y and maximum size Width/Height are added together and the number overflows. This could probably be fixed by simply reducing the maximum value for these configs, but it's really not that big of a deal; This isn't the 90s, we can spare a few bytes of wasted RAM 😛

2024-05-26 22:30 UTC, rtiangha commented
Ah, got it. Ok, definitely LGTM.

2024-05-26 22:33 UTC, merged