Update the about UI in lime_qt.
azahar-emu/azahar pull request #36
Opened 2024-04-01 22:10 UTC by BlurrySquire

I updated the UI so the right icon appears. The issue was related to the default theme name being changed but not being updated elsewhere. There might be other places where this hasn't been updated.

The button to take you to FAQ takes you to the old Citra FAQ. We should change this at some point to take you to the Lime3DS Discord Server or website.

2024-04-01 22:13 UTC, BlurrySquire commented
I'll update the FAQ button aswell. I'll make it point to the Discord server for now.

2024-04-01 22:16 UTC, BlurrySquire commented
I'm all done now with my changes. Once it builds I'll download the Windows build and test it to make sure changes work.

2024-04-02 09:59 UTC, OpenSauce04 requested changes

2024-04-02 09:59 UTC, OpenSauce04 commented on src/lime_qt/main.ui
> +    <string>FAQ (Discord)</string>
At this point, the button is no longer for an FAQ, so may as well just make it a Discord button

2024-04-02 10:10 UTC, OpenSauce04 approved these changes

2024-04-02 10:26 UTC, merged