D-pad descriptions
azahar-emu/azahar pull request #464
Opened 2024-09-24 01:10 UTC by DavidRGriswold

Add descriptions for the two D-pad options to make it clear only one should be used by most users. 

Re-write header settings in android to support optional descriptions. This should make it quite easy to add other similar notes if it is decided they are needed.

2024-09-24 12:57 UTC, kleidis requested changes

2024-09-24 12:57 UTC, kleidis commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="controller_dpad_axis_description">Some controllers will not be able to map their dpad as an axis. In that case, use the D-Pad (buttons) section below instead.</string>
```suggestion
    <string name="controller_dpad_axis_description">Some controllers may not be able to map their D-pad as an axis. If that's the case, use the D-Pad (buttons) section.</string>
```

2024-09-24 12:57 UTC, kleidis commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="controller_dpad_button_description">Only map these buttons if the D-Pad (Axis) settings above do not work with your controller.</string>
```suggestion
    <string name="controller_dpad_button_description">Only map these buttons as the D-pad if you're are facing issues with the  D-Pad (Axis) button mappings.</string>
```

2024-09-24 14:09 UTC, ghost commented
Compiled and tested, looks fine, and the code is done properly at least to my eyes

2024-09-27 12:13 UTC, OpenSauce04 commented
Merged in 8b800e58f67c8aeb96c02086439c3e435054c0a7 and af7ccc19554d38e6a5e21966baf40656fe7797bd, thanks for your contribution!

2024-09-27 12:13 UTC, closed without merging