Android: new overlay button to swap screens
azahar-emu/azahar pull request #51
Opened 2024-04-05 19:35 UTC by gperrio

Adds a new overlay button in the android build.
This allows to swap screens easily when not using a controller.
It makes the landscape layout way more usable in those conditions.

2024-04-05 20:12 UTC, OpenSauce04 requested changes

2024-04-05 20:12 UTC, OpenSauce04 commented on src/android/app/src/main/java/io/github/lime3ds/android/overlay/InputOverlay.kt
> +            )
Why does this use the X and Y position configs for completely unrelated buttons?

2024-04-05 20:12 UTC, OpenSauce04 commented on src/android/app/src/main/res/values/arrays.xml
> +    <string name="button_swap">SWAP</string>
Why is this here? Shouldn't it be with the other button strings?

2024-04-05 20:12 UTC, OpenSauce04 commented on src/android/app/src/main/res/drawable-xxxhdpi/button_swap.png
Where are the other resolutions for this image?

2024-04-05 20:12 UTC, OpenSauce04 commented on src/android/app/src/main/res/drawable-xxxhdpi/button_swap.png
This symbol doesn't match the style of the existing buttons in the touch UI:
- The existing icons are rounded, where this one is square
- The existing icons are smooth, where this one is blocky
- The existing icons use a different opacity for the symbol and the rest of the button, where this icon uses the same opacity for the whole icon

2024-04-05 20:12 UTC, OpenSauce04 commented on src/android/app/src/main/java/io/github/lime3ds/android/NativeLibrary.kt
> +
Nit: Remove this random newline

2024-04-05 20:13 UTC, gperrio commented on src/android/app/src/main/java/io/github/lime3ds/android/overlay/InputOverlay.kt
> +            )
Oh right I did that initially to align with those buttons.

2024-04-05 20:16 UTC, gperrio commented on src/android/app/src/main/res/drawable-xxxhdpi/button_swap.png
I'm afraid I am no artist.
I won't be able to make those changes.

2024-04-05 20:34 UTC, gperrio commented on src/android/app/src/main/res/values/arrays.xml
> +    <string name="button_swap">SWAP</string>
Yep, not sure why it was there.

2024-04-05 20:35 UTC, gperrio commented on src/android/app/src/main/java/io/github/lime3ds/android/NativeLibrary.kt
> +
Done

2024-04-05 21:25 UTC, OpenSauce04 commented on src/android/app/src/main/res/drawable-xxxhdpi/button_swap.png
Without the changes to the icon, this PR is unmergeable
Maintaining visual consistency in the UI's visual design is crucial

2024-04-05 21:31 UTC, gperrio commented on src/android/app/src/main/res/drawable-xxxhdpi/button_swap.png
Fair enough.
Do I delete it?

2024-04-05 21:35 UTC, OpenSauce04 commented on src/android/app/src/main/res/drawable-xxxhdpi/button_swap.png
If you believe you may come back to this PR with an updated icon eventually, you can convert the PR to a draft
Otherwise, yes you can close it if you want. It would be a shame though, as this is a genuinely useful feature!

2024-04-06 17:25 UTC, gperrio commented on src/android/app/src/main/res/drawable-xxxhdpi/button_swap.png
I pushed new versions of the icon.
Are they suitable?

2024-04-07 13:04 UTC, OpenSauce04 commented on src/android/app/src/main/res/drawable-xxxhdpi/button_swap.png
They look good at first glance, I will test this PR locally later today

2024-04-07 14:38 UTC, OpenSauce04 commented
I'll need to tweak some minor aspects of this PR, but outside of that LGTM
I will make my changes later today

2024-04-07 16:53 UTC, OpenSauce04 approved these changes

2024-04-07 21:28 UTC, BlurrySquire approved these changes
Works like expected. I tested on landscape and portrait.

2024-04-07 21:31 UTC, merged

2024-04-08 11:38 UTC, OpenSauce04 commented
@gperrio This happened because that was the email you used to commit code with. I am unable to change this retroactively unfortunately

2024-04-08 11:55 UTC, gperrio commented
OK.
I am surprised because the right email is displayed on the commit for the merge.
But it is true some of the earlier ones were done with the wrong email so I guess github kept it?

2024-04-08 12:07 UTC, gperrio commented
Well it seems like something changed in the description of the release and my email no longer appears so I don't know if you did it but problem solved.

2024-04-08 12:28 UTC, gperrio commented
@OpenSauce04 
Are you sure you cannot amend the description of commit 15c9e3e007b4ab9901b35a99ed4bdc2e4fbff523 (the latest one on master) ?
It is the only mention of that email.

2024-04-08 12:30 UTC, OpenSauce04 commented
@gperrio I can't edit the description of a commit without breaking the commit history

2024-04-08 13:08 UTC, gperrio commented
Got it.
That will teach me to configure tortoise git properly ^^